version: '3.8'
services:
  database:
    container_name: task-management
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
    ports:
      - "5433:5432"
